### ISSUE TITLE
Dot character is not highlighted in JavaScript/Typescript/CSS files

### ISSUE THREAD

**Issue by ayoisaiah** [ghifarit53/tokyonight.vim#2]
![image](https://user-images.githubusercontent.com/13372163/85851514-b9ed1d00-b7a6-11ea-9d0d-cd9c96a54ae0.png)

![image](https://user-images.githubusercontent.com/13372163/85851781-41d32700-b7a7-11ea-9bf3-1cac44eac97c.png)

In JavaScript, Typescript and CSS files, the dot character is the presented in the same way as whitespace characters. This makes it hard to distinguish between the two.

This is not a problem in other files such as Go for example:

![image](https://user-images.githubusercontent.com/13372163/85851661-05073000-b7a7-11ea-9a7b-fe569af15c7b.png)

**Comment by ghifarit53** [comment]
would you please add more details, like what plugin you use for syntax highlighting.

**Comment by ghifarit53** [comment]
![2020-06-26 at 20 48 36](https://user-images.githubusercontent.com/59758342/85864377-a82f6800-b7ee-11ea-8b59-62956065a0f5.png)

i already fixed the dot color here (will push it later), as additional info, i'm using vim-polyglot for syntax highlighting
i will add that into the README.md

**Comment by ayoisaiah** [comment]
Sure! I use vim-polyglot for syntax highlighting. I felt this issue is from this colour scheme as it isn't like this with Gruvbox (my previous colourscheme).

**Comment by ghifarit53** [comment]
done! would you please update your plugin now to see any differences

**Comment by ayoisaiah** [comment]
Thanks @ghifarit53 it works! I noticed the issue also exists for SCSS files (sass). Could you please fix that as well?
Appreciate the quick turnaround :)

**Comment by ghifarit53** [comment]
would you please screenshot the problem

**Comment by ayoisaiah** [comment]
Sure thing! Here's a SCSS file:

![image](https://user-images.githubusercontent.com/13372163/85867130-566fe900-b7c0-11ea-904c-18ed076efc6a.png)

And here's a CSS file (now fixed) after your last changes:

![image](https://user-images.githubusercontent.com/13372163/85867226-78696b80-b7c0-11ea-833f-d15a46faddf3.png)

**Comment by ghifarit53** [comment]
![2020-06-26 at 21 25 38](https://user-images.githubusercontent.com/59758342/85868027-f1ce8180-b7f3-11ea-8ad0-dd25c5c04595.png)
Done, would you check it now

**Comment by ayoisaiah** [comment]
It's perfect!

**Comment by ghifarit53** [comment]
btw why is your golang syntax different than me, because i don't remember writing that green color

**Comment by ayoisaiah** [comment]
How does it look like? Here's how mine appears:

![image](https://user-images.githubusercontent.com/13372163/85869701-f5e2ab00-b7c3-11ea-9d08-181748dfc440.png)

**Comment by ayoisaiah** [comment]
Maybe it's due to the additional plugins I use, like vim-go.

**Comment by ghifarit53** [comment]
> How does it look like? Here's how mine appears:

the green color on the parentheses are different than i wrote on the colorscheme

> Maybe it's due to the additional plugins I use, like vim-go.

yeah maybe that's why. I'll install vim-go just to make sure

**Comment by ayoisaiah** [comment]
Oh that would be from [rainbow.vim](https://github.com/luochen1990/rainbow)

**Comment by ghifarit53** [comment]
That explains the green color

anyway, thanks for your time

**Comment by ghifarit53** [comment]
hello @ayoisaiah would you mind telling me how you achieve that return character in every line ending

**Comment by ghifarit53** [comment]
just realized i've read your blog 1 month ago when setting up vim for the first time, thanks
